# Generated by Django 4.2.13 on 2026-04-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PAUSED', 'Paused')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='canvas', max_length=255)),
                ('context', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(default='General', max_length=100)),
                ('icon', models.CharField(default='zap', max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=50)),
                ('execution_type', models.CharField(blank=True, default='AUTO', max_length=50)),
                ('properties', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas_nodes', models.JSONField(default=list)),
                ('canvas_edges', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('node_type', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('position', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('WAITING', 'Waiting for approval')], default='PENDING', max_length=20)),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflow')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='NodeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('node_type', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('WAITING', 'Waiting')], default='PENDING', max_length=20)),
                ('outputs', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('step_number', models.PositiveIntegerField(default=0)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_executions', to='workflows.execution')),
            ],
            options={
                'ordering': ['step_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='execution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflow'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('actor', models.CharField(default='system', max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workflows.execution')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('approver_email', models.EmailField(blank=True, default='', max_length=254)),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('node_execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='workflows.nodeexecution')),
            ],
        ),
    ]
