# Generated by Django 6.0.4 on 2026-05-10 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('SUCCESS', 'Terminé avec succès'), ('FAILED', 'Échoué'), ('PAUSED', 'En pause — tâche humaine en attente'), ('CANCELLED', 'Annulé manuellement')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='canvas', max_length=255)),
                ('input_variables', models.JSONField(default=dict)),
                ('context', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('resume_from_node_id', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Exécution',
                'verbose_name_plural': 'Exécutions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('workflow_type', models.CharField(choices=[('Mises en production', 'Mises en production'), ('Onboarding applicatif', 'Onboarding applicatif'), ('Gestion des incidents majeurs', 'Gestion des incidents majeurs'), ('Validation sécurité', 'Validation sécurité'), ('Ouverture de flux', 'Ouverture de flux'), ('Gouvernance des changements', 'Gouvernance des changements'), ('Workflow métier custom', 'Workflow métier custom')], default='Mises en production', max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=20)),
                ('creator_name', models.CharField(default='Admin', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas_nodes', models.JSONField(default=list)),
                ('canvas_edges', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('actor', models.CharField(default='system', max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workflows.execution')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journaux d'audit",
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('node_type', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('DONE', 'Terminé'), ('FAILED', 'Échoué'), ('SKIPPED', 'Ignoré'), ('WAITING', "En attente d'action humaine"), ('RETRYING', 'Nouvelle tentative en cours')], default='PENDING', max_length=20)),
                ('outputs', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('step_number', models.PositiveIntegerField(default=0)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=0)),
                ('timeout_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_executions', to='workflows.execution')),
            ],
            options={
                'ordering': ['step_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.EmailField(blank=True, default='', max_length=254)),
                ('form_data', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('node_execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_submission', to='workflows.nodeexecution')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], max_length=20)),
                ('approver_email', models.EmailField(blank=True, default='', max_length=254)),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('required_count', models.PositiveIntegerField(default=1)),
                ('approval_type', models.CharField(choices=[('ANY', 'Au moins un approbateur'), ('ALL', 'Tous les approbateurs requis')], default='ANY', max_length=10)),
                ('node_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflows.nodeexecution')),
            ],
            options={
                'ordering': ['decided_at'],
            },
        ),
        migrations.AddField(
            model_name='execution',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflows.workflow'),
        ),
    ]
