# Generated by Django 6.0.4 on 2026-05-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='workflow_type',
            field=models.CharField(choices=[('Déploiement', 'Déploiement'), ('Onboarding', 'Onboarding'), ('Incident', 'Incident'), ('Sécurité', 'Sécurité'), ('Réseau', 'Réseau'), ('CAB', 'CAB'), ('Métier', 'Métier')], default='Déploiement', max_length=100),
        ),
    ]
