# Generated by Django 4.2.13 on 2026-04-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='category',
            field=models.CharField(choices=[('DevOps', 'DevOps'), ('QA', 'QA'), ('Développement', 'Développement'), ('Sécurité', 'Sécurité'), ('Exploitation', 'Exploitation')], default='DevOps', max_length=100),
        ),
        migrations.AddField(
            model_name='workflow',
            name='creator_name',
            field=models.CharField(default='Admin', max_length=255),
        ),
        migrations.AddField(
            model_name='workflow',
            name='itop_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workflow',
            name='priority',
            field=models.CharField(default='Non', max_length=20),
        ),
        migrations.AddField(
            model_name='workflow',
            name='solution',
            field=models.CharField(default='Kraken', max_length=100),
        ),
        migrations.AddField(
            model_name='workflow',
            name='workflow_type',
            field=models.CharField(choices=[('Mises en production', 'Mises en production'), ('Onboarding applicatif', 'Onboarding applicatif'), ('Gestion des incidents majeurs', 'Gestion des incidents majeurs'), ('Validation sécurité', 'Validation sécurité'), ('Ouverture de flux', 'Ouverture de flux'), ('Gouvernance des changements', 'Gouvernance des changements'), ('Process métier custom', 'Process métier custom')], default='Mises en production', max_length=100),
        ),
    ]
