# Generated by Django 6.0.4 on 2026-04-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflow_category_workflow_creator_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeTypeConfig',
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['created_at'], 'verbose_name': "Journal d'audit", 'verbose_name_plural': "Journaux d'audit"},
        ),
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ['-started_at'], 'verbose_name': 'Exécution', 'verbose_name_plural': 'Exécutions'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workflow', 'verbose_name_plural': 'Workflows'},
        ),
        migrations.AlterField(
            model_name='approval',
            name='decision',
            field=models.CharField(choices=[('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], max_length=20),
        ),
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('SUCCESS', 'Terminé'), ('FAILED', 'Échoué'), ('PAUSED', 'En pause')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='nodeexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('DONE', 'Terminé'), ('FAILED', 'Échoué'), ('SKIPPED', 'Ignoré'), ('WAITING', "En attente d'approbation")], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('RUNNING', 'En cours'), ('SUCCESS', 'Terminé'), ('FAILED', 'Échoué'), ('PAUSED', 'En pause')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('DONE', 'Terminé'), ('FAILED', 'Échoué'), ('SKIPPED', 'Ignoré'), ('WAITING', "En attente d'approbation")], default='PENDING', max_length=20),
        ),
    ]
