# Generated by Django 4.2.13 on 2026-04-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_delete_nodetypeconfig_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
